import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center bg-f1f3f5">
          <div className="w-[420px] bg-white py-[62px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
